<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Coding Activity 3**

**3x3**

In [8]:
import numpy as np
A = np.array([[7,5,-6],[2,5,1],[-1,-2,3]])
print ('The matrix:')
print (A)

print ('Inverse of the matrix:')
print(np.linalg.inv([[7,5,-6],[2,5,1],[-1,-2,3]]))

B = np.transpose(A)
print ('Transpose of matrix:')
print(B)

The matrix:
[[ 7  5 -6]
 [ 2  5  1]
 [-1 -2  3]]
Inverse of the matrix:
[[ 0.21794872 -0.03846154  0.44871795]
 [-0.08974359  0.19230769 -0.24358974]
 [ 0.01282051  0.11538462  0.32051282]]
Transpose of matrix:
[[ 7  2 -1]
 [ 5  5 -2]
 [-6  1  3]]


**4x4**

In [11]:
A = np.array([[7,-9,1,4],[2,4,-8,1],[1,5,2,-7],[5,-8,2,6]])
print (A)

[[ 7 -9  1  4]
 [ 2  4 -8  1]
 [ 1  5  2 -7]
 [ 5 -8  2  6]]


In [12]:
A_inv = np.linalg.inv(A)

print("Matrix: \n",A)
print("Inverse: \n",A_inv)

x = np.dot(A, A_inv)
y = np.array(x, dtype=int) 
print("Check: \n",y)

Matrix: 
 [[ 7 -9  1  4]
 [ 2  4 -8  1]
 [ 1  5  2 -7]
 [ 5 -8  2  6]]
Inverse: 
 [[-0.06718346  0.08957795  0.16709733  0.2248062 ]
 [-0.32041344  0.09388458  0.15590009  0.37984496]
 [-0.21447028 -0.04737295  0.12316968  0.29457364]
 [-0.2997416   0.06632214  0.02756245  0.3875969 ]]
Check: 
 [[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [13]:

A_trans = np.transpose(A)
print("Matrix: \n",A)
print("Transposed: \n",A_trans)

Matrix: 
 [[ 7 -9  1  4]
 [ 2  4 -8  1]
 [ 1  5  2 -7]
 [ 5 -8  2  6]]
Transposed: 
 [[ 7  2  1  5]
 [-9  4  5 -8]
 [ 1 -8  2  2]
 [ 4  1 -7  6]]
