<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/FinalExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Final Exam**

**Problem 1**

In [ ]:
import numpy as np
S1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
S2 = np.array([[89],[89],[95]])
T = np.linalg.inv(S1).dot(S2)
print(T)

[[13.]
 [57.]
 [19.]]


**Problem 2**

In [ ]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

Apinv = np.linalg.pinv(A)

x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


**Problem 3**

In [ ]:
import numpy as np
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round(),"\n")
print("The eigenvector/s is/are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
