<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Linear_Tranformation_Demo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,61]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B = np.array([[44],[128],[214]])
print(B)

#AA^-1X = B.A^-1
X = np.dot(inv_A,B)
print(X)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
[[ 44]
 [128]
 [214]]
[[-8.]
 [ 6.]
 [ 2.]]
