<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1**

In [11]:
import numpy as np
square_matrix = np.identity(5)
print(f'Square Matrix whose length is 5: \n{square_matrix}')

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Question 2**

In [12]:
upper_triangular_matrix = np.array([[1,2,3],
                                    [0,3,1],
                                    [0,0,5]])
print(f'Square matrix whose elements below the principal diagonal are zero: \n{upper_triangular_matrix}')

Square matrix whose elements below the principal diagonal are zero: 
[[1 2 3]
 [0 3 1]
 [0 0 5]]


**Question 3**

In [26]:
square_matrix = np.array ([[1,2,3,4,5],
                           [2,1,2,3,4],
                           [3,2,1,2,3],
                           [4,3,2,1,2],
                           [5,4,3,2,1]])
print('The square matrix which is symmetrical')
print(square_matrix)

The square matrix which is symmetrical
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


**Question 4**

In [23]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

inverseC = np.linalg.inv(C) 
print(inverseC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**Question 5**

In [25]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
detC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detC))

Determinant of the given matrix in Question 4:
5


**Question 6**

In [27]:
Eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])
Con = np.array([[[3.4],
                 [8.8],
                 [19.2]]])
roots = np.linalg.inv(Eq) @Con
print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
