<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Practical%20Lab%20Exam%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practical Lab Exam 1**

**Problem 1**

In [57]:
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])

WY = np.dot(W,Y)


In [38]:
#A
print(WY)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [39]:
#B
print(Z+Z)

[[0 2]
 [4 6]]


In [40]:
#C
print(3*X)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


**Problem 2**

In [58]:
#A
A = np.dot(W,Y)
B = 2*A
print(B)


[[  2  10 -12]
 [  4  12  -8]
 [  6  10   4]]


In [44]:
#B
print(WY-X)

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [48]:
#C
Z1 = np.dot(Y,W)
X2 = 2*Z
Z1 = ([[5,-7],[4,4]])
V3 = np.subtract(Z1,X2)
print(V3)

[[ 5 -9]
 [ 0 -2]]


The true statement is **Letter B**