<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Prelim Exam**

In [2]:
import numpy as np

**Question 1**

In [8]:
C = np.eye(4)

print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question 2**

In [10]:
R = C*2

print(R)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


**Question 3**

In [6]:
A = np.array([2,7,4])
B = np.array([3,9,8])

product = np.cross(A,B)
print(product)

[20 -4 -3]
