<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Python%20Exercise%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrix and Its Operations**

In [7]:
import numpy as np
#Create a NumPy program that performs the operations of the given matrices:

In [6]:
#Sum = a + b

a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])

print(a+b)

[[ 1 -3]
 [ 6  4]]


In [4]:
#Difference1 = a - b

a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])

print(a-b)

[[-11   3]
 [  2  -2]]


In [5]:
#Difference2 = b - b

a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])

print(b-b)

[[0 0]
 [0 0]]
