<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Python%20Exercise%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vector Space Operations**

In [2]:
import numpy as np
A = np.array([6,4])
B = np.array([3,-5])

print('Vector A is', A)
print("Vector B is", B)

Vector A is [6 4]
Vector B is [ 3 -5]


In [3]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.size)


(2, 3)
6


In [4]:
R = A+B
print(R)

[ 9 -1]


In [6]:
R = np.add(A,B)
R

array([ 9, -1])

In [7]:
R = np.subtract(A,B)
R

array([3, 9])

In [8]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [9]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


In [13]:
#initialize arayys
A = np.array([6,9])
B = np.array([3,7])

#compute for the cross product
output = np.cross(A,B)
print(output)

15


In [14]:
output = np.dot(A,B) #compute the dot product of A and B
print(output)

81
