<a href="https://colab.research.google.com/github/brianjavines/Linear-Algebra-58020/blob/main/Python%20Exercise%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Coding Activity 3**

x1 +x2+x3 = 5

x1+2x2+2x3 = 6

x1+2x2+3x3 = 8

In [2]:
import numpy as np
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)

B = np.array([[5],[6],[8]])

#AA^-1X = B.A^-1
X = np.dot(inv_A,B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[ 4.]
 [-1.]
 [ 2.]]
